# Generated by Django 5.1.4 on 2025-01-08 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0004_tbl_place'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tbl_place',
            new_name='tbl_scategary',
        ),
        migrations.RenameField(
            model_name='tbl_scategary',
            old_name='place_name',
            new_name='scategary_name',
        ),
    ]
