# Generated by Django 5.1.4 on 2025-01-08 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0006_tbl_place'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_scategary',
        ),
    ]
