# Generated by Django 5.1.4 on 2025-01-08 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0007_delete_tbl_scategary'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_scategary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scategary_name', models.CharField(max_length=30)),
                ('categary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_categary')),
            ],
        ),
    ]
