# Generated by Django 5.1.4 on 2025-01-15 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0008_tbl_scategary'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_registration',
        ),
    ]
