# Generated by Django 5.1.4 on 2025-03-22 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0010_tbl_adminregistration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_adminregistration',
        ),
    ]
