# Generated by Django 5.1.4 on 2025-03-22 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0011_delete_tbl_adminregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_adminregistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_name', models.CharField(max_length=30)),
                ('registration_email', models.CharField(max_length=30)),
                ('registration_photo', models.FileField(upload_to='Assets/Files/admin')),
                ('registration_password', models.CharField(max_length=30)),
            ],
        ),
    ]
