# Generated by Django 6.1.1 on 2026-09-30 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0012_tbl_adminregistration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_adminregistration',
            name='registration_email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tbl_adminregistration',
            name='registration_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tbl_adminregistration',
            name='registration_password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='tbl_adminregistration',
            name='registration_photo',
            field=models.FileField(blank=True, null=True, upload_to='Assets/Files/admin'),
        ),
        migrations.AlterField(
            model_name='tbl_categary',
            name='categary_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tbl_district',
            name='district_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tbl_place',
            name='place_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tbl_scategary',
            name='scategary_name',
            field=models.CharField(max_length=50),
        ),
    ]
