# Generated by Django 6.1.1 on 2026-09-30 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0013_alter_tbl_adminregistration_registration_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tbl_adminregistration',
            options={'ordering': ['registration_name'], 'verbose_name': 'Admin Account', 'verbose_name_plural': 'Admin Accounts'},
        ),
        migrations.AlterModelOptions(
            name='tbl_categary',
            options={'ordering': ['categary_name'], 'verbose_name': 'Admin Category', 'verbose_name_plural': 'Admin Categories'},
        ),
        migrations.AlterModelOptions(
            name='tbl_district',
            options={'ordering': ['district_name'], 'verbose_name': 'District', 'verbose_name_plural': 'Districts'},
        ),
        migrations.AlterModelOptions(
            name='tbl_place',
            options={'ordering': ['place_name'], 'verbose_name': 'Place', 'verbose_name_plural': 'Places'},
        ),
        migrations.AlterModelOptions(
            name='tbl_scategary',
            options={'ordering': ['scategary_name'], 'verbose_name': 'Admin Subcategory', 'verbose_name_plural': 'Admin Subcategories'},
        ),
        migrations.AlterField(
            model_name='tbl_adminregistration',
            name='registration_email',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='tbl_categary',
            name='categary_name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='tbl_district',
            name='district_name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='tbl_place',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='Admin.tbl_district'),
        ),
        migrations.AlterField(
            model_name='tbl_scategary',
            name='categary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='Admin.tbl_categary'),
        ),
        migrations.AddConstraint(
            model_name='tbl_place',
            constraint=models.UniqueConstraint(fields=('place_name', 'district'), name='unique_place_per_district'),
        ),
    ]
