# Generated by Django 6.1.1 on 2026-09-30 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0014_alter_tbl_adminregistration_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_audit_log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(db_index=True, max_length=100)),
                ('actor_type', models.CharField(max_length=50)),
                ('actor_name', models.CharField(max_length=100)),
                ('actor_id', models.IntegerField(blank=True, null=True)),
                ('details', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
