# Generated by Django 5.1.4 on 2025-02-04 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0008_tbl_doctor_tbl_shop'),
        ('Shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=30)),
                ('medicine_details', models.CharField(max_length=30)),
                ('medicine_price', models.CharField(max_length=30)),
                ('medicine_photo', models.FileField(upload_to='Assets/Files/medicine')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shop.tbl_category')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_shop')),
            ],
        ),
    ]
