# Generated by Django 5.1.4 on 2025-02-04 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0002_tbl_medicine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_medicine',
            name='medicine_photo',
            field=models.FileField(upload_to='Assets/Files/medicine/'),
        ),
    ]
