# Generated by Django 5.1.4 on 2025-02-05 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0003_alter_tbl_medicine_medicine_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_medicine',
        ),
    ]
