# Generated by Django 6.1.1 on 2026-09-30 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0006_tbl_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_category',
            name='category_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tbl_medicine',
            name='medicine_details',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tbl_medicine',
            name='medicine_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tbl_medicine',
            name='medicine_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tbl_stock',
            name='stock_qty',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
