# Generated by Django 6.1.1 on 2026-09-30 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0010_alter_tbl_doctor_options_and_more'),
        ('Shop', '0007_alter_tbl_category_category_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tbl_category',
            options={'ordering': ['category_name'], 'verbose_name': 'Medicine Category', 'verbose_name_plural': 'Medicine Categories'},
        ),
        migrations.AlterModelOptions(
            name='tbl_medicine',
            options={'ordering': ['medicine_name'], 'verbose_name': 'Medicine', 'verbose_name_plural': 'Medicines'},
        ),
        migrations.AlterModelOptions(
            name='tbl_stock',
            options={'ordering': ['-id'], 'verbose_name': 'Stock Entry', 'verbose_name_plural': 'Stock Entries'},
        ),
        migrations.AlterField(
            model_name='tbl_category',
            name='category_name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='tbl_medicine',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='Shop.tbl_category'),
        ),
        migrations.AlterField(
            model_name='tbl_medicine',
            name='medicine_status',
            field=models.IntegerField(choices=[(0, 'Over-The-Counter'), (1, 'Prescription Required')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='tbl_medicine',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='Guest.tbl_shop'),
        ),
        migrations.AddConstraint(
            model_name='tbl_medicine',
            constraint=models.CheckConstraint(condition=models.Q(('medicine_price__gte', 0)), name='valid_medicine_price'),
        ),
        migrations.AddConstraint(
            model_name='tbl_stock',
            constraint=models.CheckConstraint(condition=models.Q(('stock_qty__gte', 0)), name='valid_stock_qty'),
        ),
    ]
