# Generated by Django 5.1.4 on 2025-01-15 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0008_tbl_scategary'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_name', models.CharField(max_length=30)),
                ('registration_email', models.CharField(max_length=30)),
                ('registration_contact', models.CharField(max_length=30)),
                ('registration_address', models.CharField(max_length=30)),
                ('registration_photo', models.CharField(max_length=30)),
                ('registration_password', models.CharField(max_length=30)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
            ],
        ),
    ]
