# Generated by Django 5.1.4 on 2025-01-15 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_registration',
            name='registration_photo',
        ),
    ]
