# Generated by Django 5.1.4 on 2025-01-15 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0002_remove_tbl_registration_registration_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_registration',
        ),
    ]
