# Generated by Django 5.1.4 on 2025-01-28 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0010_tbl_adminregistration'),
        ('Guest', '0004_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=30)),
                ('doctor_email', models.CharField(max_length=30)),
                ('doctor_contact', models.CharField(max_length=30)),
                ('doctor_photo', models.FileField(upload_to='Assets/Files/doctor')),
                ('doctor_licese', models.FileField(upload_to='Assets/Files/doctor')),
                ('doctor_password', models.CharField(max_length=30)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
            ],
        ),
    ]
