# Generated by Django 5.1.4 on 2025-01-28 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0010_tbl_adminregistration'),
        ('Guest', '0005_tbl_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=30)),
                ('shop_email', models.CharField(max_length=30)),
                ('shop_contact', models.CharField(max_length=30)),
                ('shop_address', models.CharField(max_length=30)),
                ('shop_photo', models.FileField(upload_to='Assets/Files/shop')),
                ('shop_licese', models.FileField(upload_to='Assets/Files/shop')),
                ('shop_password', models.CharField(max_length=30)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
            ],
        ),
    ]
