# Generated by Django 5.1.4 on 2025-01-28 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0006_tbl_shop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_shop',
            name='place',
        ),
        migrations.DeleteModel(
            name='tbl_doctor',
        ),
        migrations.DeleteModel(
            name='tbl_shop',
        ),
    ]
