# Generated by Django 6.1.1 on 2026-09-30 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0008_tbl_doctor_tbl_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_doctor',
            name='doctor_email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tbl_doctor',
            name='doctor_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tbl_doctor',
            name='doctor_password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='tbl_registration',
            name='registration_address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tbl_registration',
            name='registration_email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tbl_registration',
            name='registration_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tbl_registration',
            name='registration_password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='tbl_shop',
            name='shop_address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tbl_shop',
            name='shop_email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tbl_shop',
            name='shop_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tbl_shop',
            name='shop_password',
            field=models.CharField(max_length=128),
        ),
    ]
