# Generated by Django 6.1.1 on 2026-09-30 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0014_alter_tbl_adminregistration_options_and_more'),
        ('Guest', '0009_alter_tbl_doctor_doctor_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tbl_doctor',
            options={'ordering': ['doctor_name'], 'verbose_name': 'Doctor', 'verbose_name_plural': 'Doctors'},
        ),
        migrations.AlterModelOptions(
            name='tbl_registration',
            options={'ordering': ['registration_name'], 'verbose_name': 'User / Patient', 'verbose_name_plural': 'Users / Patients'},
        ),
        migrations.AlterModelOptions(
            name='tbl_shop',
            options={'ordering': ['shop_name'], 'verbose_name': 'Shop / Pharmacy', 'verbose_name_plural': 'Shops / Pharmacies'},
        ),
        migrations.AlterField(
            model_name='tbl_doctor',
            name='doctor_email',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='tbl_doctor',
            name='doctor_status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Approved'), (2, 'Rejected')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='tbl_doctor',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='Admin.tbl_place'),
        ),
        migrations.AlterField(
            model_name='tbl_registration',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='Admin.tbl_place'),
        ),
        migrations.AlterField(
            model_name='tbl_registration',
            name='registration_email',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='tbl_shop',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shops', to='Admin.tbl_place'),
        ),
        migrations.AlterField(
            model_name='tbl_shop',
            name='shop_email',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='tbl_shop',
            name='shop_status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Approved'), (2, 'Rejected')], db_index=True, default=0),
        ),
    ]
