# Generated by Django 5.1.4 on 2025-01-22 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Guest', '0004_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_complaints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaints_subject', models.CharField(max_length=255)),
                ('complaints_content', models.TextField()),
                ('complaints_status', models.IntegerField(default=0)),
                ('complaints_date', models.DateTimeField(auto_now_add=True)),
                ('complaints_reply', models.TextField(blank=True, null=True)),
                ('complaints_reply_date', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_registration')),
            ],
        ),
    ]
