# Generated by Django 5.1.4 on 2025-02-05 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0008_tbl_doctor_tbl_shop'),
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_details', models.CharField(max_length=255)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('request_status', models.IntegerField(default=0)),
                ('dotor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_doctor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_registration')),
            ],
        ),
    ]
