# Generated by Django 5.1.4 on 2025-02-18 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0008_tbl_doctor_tbl_shop'),
        ('Shop', '0006_tbl_stock'),
        ('User', '0002_tbl_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_amount', models.CharField(max_length=255)),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('booking_status', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_registration')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_status', models.IntegerField(default=0)),
                ('cart_quantity', models.CharField(max_length=30)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.tbl_booking')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shop.tbl_medicine')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription_file', models.FileField(upload_to='Assets/Files/Doctor/Prescription')),
                ('prescription_date', models.DateTimeField(auto_now_add=True)),
                ('requestpres', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.tbl_request')),
            ],
        ),
        migrations.AddField(
            model_name='tbl_booking',
            name='prescription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.tbl_prescription'),
        ),
    ]
