# Generated by Django 5.1.4 on 2025-02-18 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_tbl_booking_tbl_cart_tbl_prescription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_booking',
            name='prescription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='User.tbl_prescription'),
        ),
    ]
