# Generated by Django 5.1.4 on 2025-02-25 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_alter_tbl_booking_prescription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_cart',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='tbl_cart',
            name='medicine',
        ),
        migrations.DeleteModel(
            name='tbl_booking',
        ),
        migrations.DeleteModel(
            name='tbl_cart',
        ),
    ]
