# Generated by Django 6.1.1 on 2026-09-30 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0009_alter_tbl_doctor_doctor_email_and_more'),
        ('User', '0007_tbl_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_cart',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='tbl_rating',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_registration'),
        ),
        migrations.AlterField(
            model_name='tbl_booking',
            name='booking_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tbl_booking',
            name='prescription',
            field=models.FileField(blank=True, null=True, upload_to='Assets/Files/User/Prescription'),
        ),
        migrations.AlterField(
            model_name='tbl_cart',
            name='cart_quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='tbl_rating',
            name='rating_data',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='tbl_rating',
            name='user_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='tbl_rating',
            name='user_review',
            field=models.TextField(),
        ),
    ]
