# Generated by Django 6.1.1 on 2026-09-30 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0010_alter_tbl_doctor_options_and_more'),
        ('Shop', '0008_alter_tbl_category_options_and_more'),
        ('User', '0008_tbl_cart_unit_price_tbl_rating_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tbl_booking',
            options={'ordering': ['-booking_date'], 'verbose_name': 'Order / Booking', 'verbose_name_plural': 'Orders / Bookings'},
        ),
        migrations.AlterModelOptions(
            name='tbl_cart',
            options={'ordering': ['-id'], 'verbose_name': 'Cart Item', 'verbose_name_plural': 'Cart Items'},
        ),
        migrations.AlterModelOptions(
            name='tbl_complaints',
            options={'ordering': ['-complaints_date'], 'verbose_name': 'User Complaint', 'verbose_name_plural': 'User Complaints'},
        ),
        migrations.AlterModelOptions(
            name='tbl_prescription',
            options={'ordering': ['-prescription_date'], 'verbose_name': 'Doctor Prescription', 'verbose_name_plural': 'Doctor Prescriptions'},
        ),
        migrations.AlterModelOptions(
            name='tbl_rating',
            options={'ordering': ['-datetime'], 'verbose_name': 'Doctor Rating & Review', 'verbose_name_plural': 'Doctor Ratings & Reviews'},
        ),
        migrations.AlterModelOptions(
            name='tbl_request',
            options={'ordering': ['-request_date'], 'verbose_name': 'Consultation Request', 'verbose_name_plural': 'Consultation Requests'},
        ),
        migrations.AlterField(
            model_name='tbl_booking',
            name='booking_status',
            field=models.IntegerField(choices=[(0, 'Active Cart'), (1, 'Checkout Initiated'), (2, 'Paid / Placed'), (3, 'Packing'), (4, 'Delivered')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='tbl_booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='Guest.tbl_registration'),
        ),
        migrations.AlterField(
            model_name='tbl_cart',
            name='cart_status',
            field=models.IntegerField(choices=[(0, 'In Cart'), (1, 'Ordered')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='tbl_complaints',
            name='complaints_status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Replied')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='tbl_complaints',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='Guest.tbl_registration'),
        ),
        migrations.AlterField(
            model_name='tbl_prescription',
            name='requestpres',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='User.tbl_request'),
        ),
        migrations.AlterField(
            model_name='tbl_rating',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='Guest.tbl_doctor'),
        ),
        migrations.AlterField(
            model_name='tbl_rating',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_ratings', to='Guest.tbl_registration'),
        ),
        migrations.AlterField(
            model_name='tbl_request',
            name='dotor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultation_requests', to='Guest.tbl_doctor'),
        ),
        migrations.AlterField(
            model_name='tbl_request',
            name='request_status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Prescribed / Accepted')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='tbl_request',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultation_requests', to='Guest.tbl_registration'),
        ),
        migrations.AddIndex(
            model_name='tbl_rating',
            index=models.Index(fields=['doctor', '-datetime'], name='rating_doc_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='tbl_booking',
            constraint=models.CheckConstraint(condition=models.Q(('booking_amount__gte', 0)), name='valid_booking_amount'),
        ),
        migrations.AddConstraint(
            model_name='tbl_cart',
            constraint=models.CheckConstraint(condition=models.Q(('cart_quantity__gte', 1)), name='valid_cart_quantity'),
        ),
        migrations.AddConstraint(
            model_name='tbl_cart',
            constraint=models.UniqueConstraint(fields=('booking', 'medicine'), name='unique_medicine_per_booking'),
        ),
        migrations.AddConstraint(
            model_name='tbl_rating',
            constraint=models.CheckConstraint(condition=models.Q(('rating_data__gte', 1), ('rating_data__lte', 5)), name='valid_rating_range'),
        ),
    ]
