# Generated by Django 5.1.4 on 2025-02-11 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_prescription',
        ),
    ]
