# Generated by Django 5.1.4 on 2025-02-11 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Doctor', '0002_delete_tbl_prescription'),
        ('User', '0002_tbl_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription_file', models.FileField(upload_to='Assets/Files/Doctor/Prescription')),
                ('prescription_date', models.DateTimeField(auto_now_add=True)),
                ('requestpres', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.tbl_request')),
            ],
        ),
    ]
