# Generated by Django 5.1.4 on 2025-02-18 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_prescription',
        ),
    ]
