# Generated by Django 5.1.4 on 2025-03-15 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Doctor', '0004_delete_tbl_prescription'),
        ('Guest', '0008_tbl_doctor_tbl_shop'),
        ('User', '0006_tbl_booking_tbl_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_name', models.CharField(max_length=30)),
                ('disease_symptoms', models.CharField(max_length=30)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_doctor')),
                ('reqpre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.tbl_request')),
            ],
        ),
    ]
