# Generated by Django 6.1.1 on 2026-09-30 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0005_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_disease',
            name='disease_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tbl_disease',
            name='disease_symptoms',
            field=models.TextField(),
        ),
    ]
