# Generated by Django 6.1.1 on 2026-09-30 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0006_alter_tbl_disease_disease_name_and_more'),
        ('Guest', '0010_alter_tbl_doctor_options_and_more'),
        ('User', '0009_alter_tbl_booking_options_alter_tbl_cart_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tbl_disease',
            options={'ordering': ['-id'], 'verbose_name': 'Disease Prediction Record', 'verbose_name_plural': 'Disease Prediction Records'},
        ),
        migrations.AlterField(
            model_name='tbl_disease',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disease_predictions', to='Guest.tbl_doctor'),
        ),
        migrations.AlterField(
            model_name='tbl_disease',
            name='reqpre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disease_predictions', to='User.tbl_request'),
        ),
    ]
