# Generated by Django 6.1.1 on 2026-09-30 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0007_alter_tbl_disease_options_alter_tbl_disease_doctor_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tbl_disease',
            options={'ordering': ['-prediction_date', '-id'], 'verbose_name': 'Disease Prediction Record', 'verbose_name_plural': 'Disease Prediction Records'},
        ),
        migrations.AddField(
            model_name='tbl_disease',
            name='confidence_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tbl_disease',
            name='prediction_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
